tree:
  -
    id: da9d3199-233b-4ae3-8266-3139ef07bc61
    entry: 1cc784ea-accd-4637-9ee7-198356a1f7e1
    data:
      color: primary-500
      icon: icons/finanz_und_rechnungswesen-color.png
      short_description: "Préparation des états financiers mensuels, trimestriels et annuels, conformément aux directives de l'entreprise"
      members:
        - cf10db05-4999-4047-8a1d-313e5d6ec506
        - da2c9718-6ba9-4d8c-96e8-2870b553320c
  -
    id: c8dc7bb5-9e47-4162-b2ad-6c9e32ef7449
    entry: 1838e804-7afe-42fb-96d5-c5606a8726b5
    title: 'Conseil juridique et fiscal'
    data:
      color: secondary-500
      icon: icons/steuer_und_rechtsberatung-color.png
      short_description: 'Planification et conseils fiscaux, restructurations, rachats et réorganisations'
      members:
        - 64392178-de12-4f8f-b721-bd377074c85b
        - 6aad6a4e-8ef2-4a56-af31-cc41db3cb34d
  -
    id: c81f7519-2e82-4d96-841f-d6874132f0a6
    entry: f4c03fa2-b7a8-41a5-b2d9-587bb76981f0
    title: 'Conseil en économie et en gestion'
    data:
      color: gray-800
      icon: icons/wirtschafts_und_unternehmensberatung-color-1739883775.png
      short_description: 'Règlement, conseils sur la forme de société ou sur la création ou la liquidation de sociétés'
      members:
        - da2c9718-6ba9-4d8c-96e8-2870b553320c
        - ce52704e-1d7d-4d44-af79-04a4103573ed
  -
    id: 86acf353-62a8-4d41-981e-550243f1e3a2
    entry: f85fc4fe-f106-4f8e-b982-51b32b122c58
    title: 'Conseil en matière de salaires et de ressources humaines'
    data:
      color: secondary-500
      icon: icons/salaer_und_human_resources_beratung-color.png
      short_description: 'Paie, ressources humaines'
      members:
        - aaae87f7-126d-491e-b7c3-bb152adf07aa
  -
    id: 15ed27d6-beb7-4dc0-8784-7ad116571fa4
    entry: 4091bb77-124c-4138-a351-cebc79651457
    data:
      color: gray-800
      icon: icons/wirtschaftsprufung-color.png
      short_description: 'Audit des états financiers annuels et consolidés, audit des fondations (fondations qualifiées)'
      members:
        - be019033-f335-4edd-b893-eccac36c57bd
        - 56d24158-7e42-4f87-b7c3-5d3c3f6e3259
  -
    id: 2582e445-0106-4b86-a1fe-5fff3d130b0c
    entry: a45c9753-037f-477f-814b-66b926482171
    data:
      color: primary-500
      icon: icons/mehrwertsteuerberatung-color.png
      short_description: 'at Fiscal Representations in Switzerland and abroad through our international network'
      members:
        - ce52704e-1d7d-4d44-af79-04a4103573ed
