sections:
  main:
    display: Main
    fields:
      -
        import: color
      -
        handle: icon
        field:
          mode: list
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Icon
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          read_only: false
          container: assets
          folder: icons
          localizable: true
      -
        handle: short_description
        field:
          antlers: false
          display: 'Short Description'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          read_only: false
          localizable: true
