title: 'Sekretariat & Marketing'
use_meta_keywords: false
no_index_page: false
no_follow_links: false
sitemap_priority: '0.5'
sitemap_changefreq: daily
override_twitter_settings: false
override_twitter_card_settings: false
updated_by: 3574a48a-d509-4c9e-9e37-5b83b6cfdc78
updated_at: 1652775208
blueprint: team_tags
localizations:
  en:
    title: 'Secretariat & Marketing'
    slug: sekretariat-und-marketing
    updated_by: 3574a48a-d509-4c9e-9e37-5b83b6cfdc78
    updated_at: 1652775310
  fr:
    title: 'Secrétariat & Marketing'
    slug: sekretariat-und-marketing
    updated_by: 3574a48a-d509-4c9e-9e37-5b83b6cfdc78
    updated_at: 1652775342
