title: Wirtschaftsprüfung
use_meta_keywords: false
no_index_page: false
no_follow_links: false
sitemap_priority: '0.5'
sitemap_changefreq: daily
override_twitter_settings: false
override_twitter_card_settings: false
updated_by: 3574a48a-d509-4c9e-9e37-5b83b6cfdc78
updated_at: 1648202960
blueprint: team_tags
localizations:
  en:
    title: Auditing
    slug: wirtschaftspruefung
    updated_by: 3574a48a-d509-4c9e-9e37-5b83b6cfdc78
    updated_at: 1649838600
  fr:
    title: Audit
    slug: wirtschaftspruefung
    updated_by: 3574a48a-d509-4c9e-9e37-5b83b6cfdc78
    updated_at: 1649838603
