title: 'News / Blogazin'
use_meta_keywords: false
no_index_page: false
no_follow_links: false
sitemap_priority: '0.5'
sitemap_changefreq: daily
override_twitter_settings: false
updated_by: b1c36291-e863-41f3-8c6f-b18dd4f22325
updated_at: 1671203025
blueprint: news_tags
localizations:
  en:
    title: 'News / Blogazin'
    slug: news-blogazin
    updated_by: b1c36291-e863-41f3-8c6f-b18dd4f22325
    updated_at: 1671203046
  fr:
    title: 'News / Blogazin'
    slug: news-blogazin
    updated_by: b1c36291-e863-41f3-8c6f-b18dd4f22325
    updated_at: 1671203062
