theme_color: '#179CD7'
theme_color_dark: '#179CD7'
google_fonts_link: 'https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap'
